---
- hosts: javaserver
  become: yes
  vars:
   
    myvar2: tree
    myvar3: apache2
  tasks: 
    - name: I want to display variable
      debug: 
          msg: "{{myvar1}}"

    - name: I want to install tree,apache2
      apt: 
        name: "{{item}}"
        state: present
      loop: 
      
      - "{{myvar2}}"
      - "{{myvar3}}"