---
- hosts: javaserver
  become: yes
  vars:
    myvar1: git
    myvar2: tree
    myvar3: apache2
  tasks: 
    - name: I want to display variable
      debug: 
          msg: "{{myvar1}}"

    - name: I want to install git
      apt: 
        name: "{{item}}"
        state: present
      loop: 
      - "{{myvar1}}"
      - "{{myvar2}}"
      - "{{myvar3}}"