---
- hosts: all
  become: yes
  tasks:

    - name: Install tree
      apt:
        name: tree
        state: present

    - name: install apache2
      apt:
        name: apache2
        state: present

    - name: Start Apache service
      service:
        name: apache2
        state: started

  

