---
- hosts: all
  become: yes
  tasks:

    - name: Install tree
      apt:
        name: tree
        state: present
      tags: mytree


    - name: Install wget
      apt:
        name: wget
        state: present
      tags: mywget
